### ISSUE TITLE
AttributeError: module 'numcodecs' has no attribute 'Blosc'

### ISSUE THREAD

**Issue by agladstein** [tskit-dev/tszip#25]
I'm trying out tszip and I got the same error when I tried it out on my simulation and also the example from the docs.

On mac, I imported tszip 0.1.0 with pip

```
import msprime
import tszip

ts = msprime.simulate(10, random_seed=1)
tszip.compress(ts, "simulation.trees.tsz")
```

I got the error:
```
Traceback (most recent call last):
  File "src/data/test_tszip.py", line 5, in <module>
    tszip.compress(ts, "simulation.trees.tsz")
  File "/Users/agladsteinNew/.local/share/virtualenvs/cnn_classify_demography-zZ5GtBgD/lib/python3.7/site-packages/tszip/compression.py", line 97, in compress
    compress_zarr(ts, root, variants_only=variants_only)
  File "/Users/agladsteinNew/.local/share/virtualenvs/cnn_classify_demography-zZ5GtBgD/lib/python3.7/site-packages/tszip/compression.py", line 240, in compress_zarr
    compressor = numcodecs.Blosc(cname='zstd', clevel=9, shuffle=numcodecs.Blosc.SHUFFLE)
AttributeError: module 'numcodecs' has no attribute 'Blosc'
```

I'm guessing a dependency issue, but I'm not sure.

**Comment by jeromekelleher** [comment]
Thanks for trying this out @agladstein! Sounds like you might have an older version of ``numcodecs`` installed and we probably need to put a minimum version into ``setup.py``. What does

```
import numcodecs
print(numcodecs.__version__)
```
give you?

**Comment by agladstein** [comment]
I have 0.5.5

**Comment by agladstein** [comment]
I updated to `numcodecs` 0.6.3, and the example from docs worked.

**Comment by jeromekelleher** [comment]
OK, thanks @agladstein, this is great to know. I'm closing this in favour of #27.
