### ISSUE TITLE
ValueError: codec not available: 'blosc'

### ISSUE THREAD

**Issue by gtsambos** [tskit-dev/tszip#29]
hullo, this is possibly not an 'issue' so much as my own problem.
I'm trying to decompress your 1000G tree sequences from Zenodo, but am getting this error message. Do you know what might be going on here?

```
6200D-132482-M:raw gtsambos$ tsunzip 1kg_chr19.trees.tsz 
Traceback (most recent call last):
  File "/Users/gtsambos/miniconda3/bin/tsunzip", line 10, in <module>
    sys.exit(tsunzip_main())
  File "/Users/gtsambos/miniconda3/lib/python3.7/site-packages/tszip/cli.py", line 170, in tsunzip_main
    main(args)
  File "/Users/gtsambos/miniconda3/lib/python3.7/site-packages/tszip/cli.py", line 153, in main
    run_decompress(args)
  File "/Users/gtsambos/miniconda3/lib/python3.7/site-packages/tszip/cli.py", line 139, in run_decompress
    ts = tszip.decompress(file_arg)
  File "/Users/gtsambos/miniconda3/lib/python3.7/site-packages/tszip/compression.py", line 113, in decompress
    return decompress_zarr(root)
  File "/Users/gtsambos/miniconda3/lib/python3.7/site-packages/tszip/compression.py", line 282, in decompress_zarr
    coordinates = root["coordinates"][:]
  File "/Users/gtsambos/miniconda3/lib/python3.7/site-packages/zarr/hierarchy.py", line 326, in __getitem__
    synchronizer=self._synchronizer, cache_attrs=self.attrs.cache)
  File "/Users/gtsambos/miniconda3/lib/python3.7/site-packages/zarr/core.py", line 124, in __init__
    self._load_metadata()
  File "/Users/gtsambos/miniconda3/lib/python3.7/site-packages/zarr/core.py", line 141, in _load_metadata
    self._load_metadata_nosync()
  File "/Users/gtsambos/miniconda3/lib/python3.7/site-packages/zarr/core.py", line 169, in _load_metadata_nosync
    self._compressor = get_codec(config)
  File "/Users/gtsambos/miniconda3/lib/python3.7/site-packages/numcodecs/registry.py", line 36, in get_codec
    raise ValueError('codec not available: %r' % codec_id)
ValueError: codec not available: 'blosc'
```

**Comment by jeromekelleher** [comment]
This is an upstream problem with zarr, see https://github.com/zarr-developers/numcodecs/issues/196.

Basically, zarr didn't build properly but went ahead and installed itself anyway. You probably want to reinstall zarr using conda. (Did you install tszip with pip or conda?)

**Comment by LukeAndersonTrocme** [comment]
Likely still an upstream problem with zarr, but wanted to chime in and say that on my local machine even after 
```
conda install zarr --force-reinstall
```
and
```
conda install tszip --force-reinstall
```
I get the same issue as described above.

This being said, things work perfectly fine on my compute cluster, so it's likely an issue with my local environment.
