### ISSUE TITLE
Latest version of numcodecs doesn't build

### ISSUE THREAD

**Issue by gtsambos** [tskit-dev/tszip#30]
Hello, was running into issues installing `tszip` because of the `numcodecs` build failing. It seems to be a [common issue](https://github.com/napari/napari/issues/665). When I then manually installed an earlier version of numcodecs (0.6.2), everything worked fine. Perhaps worth a note in the Installation docs?

**Comment by gtsambos** [comment]
Ah, sadly, tsunzip installs but then doesn't actually work, this time because of some problem with `blosc`
```
6200D-132482-M:0.raw gtsambos$ tsunzip 1kg_chr21.trees.tsz 
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/tsunzip", line 8, in <module>
    sys.exit(tsunzip_main())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tszip/cli.py", line 170, in tsunzip_main
    main(args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tszip/cli.py", line 153, in main
    run_decompress(args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tszip/cli.py", line 139, in run_decompress
    ts = tszip.decompress(file_arg)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tszip/compression.py", line 113, in decompress
    return decompress_zarr(root)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tszip/compression.py", line 282, in decompress_zarr
    coordinates = root["coordinates"][:]
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/zarr/hierarchy.py", line 326, in __getitem__
    synchronizer=self._synchronizer, cache_attrs=self.attrs.cache)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/zarr/core.py", line 124, in __init__
    self._load_metadata()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/zarr/core.py", line 141, in _load_metadata
    self._load_metadata_nosync()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/zarr/core.py", line 169, in _load_metadata_nosync
    self._compressor = get_codec(config)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numcodecs/registry.py", line 36, in get_codec
    raise ValueError('codec not available: %r' % codec_id)
ValueError: codec not available: 'blosc'
```

**Comment by gtsambos** [comment]
It all worked when I installed everything with conda instead? 🤷‍♂

**Comment by jeromekelleher** [comment]
This is a troublesome upstream issue @gtsambos (github.com/zarr-developers/numcodecs/issues/210), and there doesn't seem to be much we can do about it. Basically, numcodecs will install without errors even if some of the codecs fail to compile. Blosc seems to be a problem on OSX. 

I think we probably will have to add a note to the installation docs, or else perhaps do a manual check at import time and raise a specific error telling the user to fix their numcodecs installation.

**Comment by jeromekelleher** [comment]
Going to close this due to inactivity.
